import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MenubarDemo } from "@/components/ui/topbar";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors/>
        <MenubarDemo />
        {children}
      </body>
    </html>
  );
}
